# apiVersion: v1
# kind: Service
# metadata:
#   name: password-generator-service
# spec:
#   selector:
#     app: password-generator
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000
#   type: NodePort
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ default .Chart.Name .Values.fullnameOverride }}
  labels: 
    app: {{ .Values.appLabel  }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 8000
  selector:
    app: {{ .Values.appLabel }}  # Match the label used in deployment

